apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - kafka.yaml
  - kafka-init-job.yaml
  - kong.yaml
  - kong-db.yaml
  - kong-init-job.yaml
  - localstack.yaml
  - redis.yaml
  - traefik-config.yaml
  - zookeeper.yaml
