---
# user-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: user_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
# template-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: template-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: template_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
# file-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: file-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: file_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
# audit-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: audit-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: audit_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
# api-key-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: api-key-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: apikey_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
# webhook-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: webhook-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: webhook_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
# kong-db credentials
apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
  namespace: dynadoc
type: Opaque
stringData:
  POSTGRES_DB: kong
  POSTGRES_USER: kong
  POSTGRES_PASSWORD: kong
