apiVersion: v1
kind: Secret
metadata:
  name: jwt-private-secret
  namespace: dynadoc
type: Opaque
stringData:
  jwt-private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiuMQqq72a8cHg
    LzKsCGYyP56Yhgzm+GJHfceVDU/yfuhSPNEkmFjgksgMpWBXqsPto7q8xjSAeE2b
    tGnralxzMO3/i0unJk7CKEAte5yvC2ppK6P9j1dG/2fFZ9snYOqouSukTS14uWVe
    ve3bu/y3DkLK9EVuDi+9YFYUBS+y1i9Xn5xGCW63s/AL8CSlGD5BKHnPHeO02+pl
    kQHzAiE4vUAtycvztr3O9C8KpsRljmoCf/Ia1+bggeME33bGkhq+Pqj5IwCVfuPb
    UKEUsYwfPlgNLe2nPH+txgx/e6aZsocRNbclkSskNBlp+OY20EhUxYHqQ2rJu9HI
    doRFMkB9AgMBAAECggEAB9agkasKgmPKBZq7of7ylOuTIA14oolzyulTodaz4Ff9
    wkGU1CKbL2nREkJ6IlopWRgIvaF+AHOrG2IrGWon3QWnnuZ1HogxUlfkuLwqYOIK
    8XKzq6bWwU0G0OlokwKvmX3EzPb8+hwfw04g+EBO02H8uv2RONS2nU4xcoJW2QWC
    gdYXxY92yf2hBOdmmKd0ZotUAC5WhkBOmsdku6n3+8yyaP7qxuTLYm2o3gZNH1Ry
    cm88pa/mlCuzwoXxslgGekp09Y8xyAoByHGOQyWO20VSFonVj05knzgAObm6MDyI
    Y74V4+qn/dVDcEjUucVP0oAoCwxwr5cRX3/cjGDVyQKBgQDOaH/70tRilFBoZwGc
    e5bzZTmRUonP/93c5useXokJATsYdq5ieaRDXtBbc+bEuRFNZp32W8459xCJIMxN
    wXmaYnPRiannYSURhmyAKyzrrrEGMAXvZPk06pWf4Se66wYa8XavQUZpU2xy0F4B
    wzwjbuxrNubuJayJASEH/FCBuQKBgQDJ0UDyRUAF6w2vqwc3SBm/Pat4I3LAkcSb
    gJYTReM+KW6/0W9iRmxzTuzy1qoTdy6Y6zL3YKb1RpPGm4KjbG+rGKJUGWkzikSE
    aUpcAtQ2kKQ9SlbcHs49MvR2SlyrUb/tOhD4dcHb1Z3WqrWn1wWBeWtDgMIBgHf1
    nlXqWrLm5QKBgQCDWKxYq0jLkmW4ihPUaDEeoYOInmVkHwYn1Co6IR5CxK2+W4eM
    0qtc07DzAUYQWVRRVMOgSbtp13aGTIC12jBvtcbNyDR+MKtOA6R3ywHC2F99+IFO
    XYrXyY99NeH6aCRycMV9sKQF0jhot3+az4otYiC/+Sfq075/UGCcnEr+wQKBgD73
    IVs1Dd+K0W9QXeT6gsXu2LOX47J/CCc3/BqxQE/hn2MLVcQEkst7AWRWYyPFmG0v
    XGxf5Fc8GNjrJdwU9dYcznCMqQzig7QIIaIJY+pOQF+69NSia9geMLVDSBxPWiEK
    b8cE/mG3CRKzmg9uf5JArp2V63GKgmLIbqe6enydAoGAD8U9TWRDG6BPZTZ/Uc2b
    zX6BGYESZPR8Ssc1+py1WmxvjT/4C2QRGtjj/cQ89Z5cHnYim0uqRrnEjiVyjhUH
    esKspGKSMZeNxGdCDJB/ADd8RvZUX9avA7vMLEGOJ4ycv+K89S7KVrIvacjMdnk8
    X9WYlGlOfKygnTigYZSwo4k=
    -----END PRIVATE KEY-----
