apiVersion: v1
kind: Secret
metadata:
  name: kong-jwt-secret
  namespace: dynadoc
type: Opaque
stringData:
  jwt-public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAorjEKqu9mvHB4C8yrAhm
    Mj+emIYM5vhiR33HlQ1P8n7oUjzRJJhY4JLIDKVgV6rD7aO6vMY0gHhNm7Rp62pc
    czDt/4tLpyZOwihALXucrwtqaSuj/Y9XRv9nxWfbJ2DqqLkrpE0teLllXr3t27v8
    tw5CyvRFbg4vvWBWFAUvstYvV5+cRglut7PwC/AkpRg+QSh5zx3jtNvqZZEB8wIh
    OL1ALcnL87a9zvQvCqbEZY5qAn/yGtfm4IHjBN92xpIavj6o+SMAlX7j21ChFLGM
    Hz5YDS3tpzx/rcYMf3ummbKHETW3JZErJDQZafjmNtBIVMWB6kNqybvRyHaERTJA
    fQIDAQAB
    -----END PUBLIC KEY-----

