apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-cm
  namespace: observability
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-svc.observability.svc.cluster.local:9090
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 15s
          queryTimeout: 60s
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: tempo

      - name: Loki
        type: loki
        uid: loki
        url: http://loki-svc.observability.svc.cluster.local:3100
        access: proxy
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"trace_id":"(\w+)"'
              name: TraceID
              url: "${__value.raw}"
              urlDisplayLabel: "View Trace"

      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo-svc.observability.svc.cluster.local:3200
        access: proxy
        jsonData:
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: loki
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: -1m
            spanEndTimeShift: 1m
            filterByTraceID: true
            filterBySpanID: false

      - name: AlertManager
        type: alertmanager
        uid: alertmanager
        url: http://alertmanager-svc.observability.svc.cluster.local:9093
        access: proxy
        jsonData:
          implementation: prometheus
