apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-key/
  - audit/
  - file/
  - notification/
  - swagger/
  - template/
  - user/
  - webhook/
  - worker-headless-svcs.yaml
