apiVersion: v1
kind: Service
metadata:
  name: template-queue
  namespace: dynadoc
spec:
  clusterIP: None
  selector:
    app: template-queue
---
apiVersion: v1
kind: Service
metadata:
  name: file-queue
  namespace: dynadoc
spec:
  clusterIP: None
  selector:
    app: file-queue
---
apiVersion: v1
kind: Service
metadata:
  name: template-consumer
  namespace: dynadoc
spec:
  clusterIP: None
  selector:
    app: template-consumer
---
apiVersion: v1
kind: Service
metadata:
  name: file-consumer
  namespace: dynadoc
spec:
  clusterIP: None
  selector:
    app: file-consumer
---
apiVersion: v1
kind: Service
metadata:
  name: audit-consumer
  namespace: dynadoc
spec:
  clusterIP: None
  selector:
    app: audit-consumer
