apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmaps/
  - alertmanager.yaml
  - cadvisor.yaml
  - grafana.yaml
  - kube-state-metrics.yaml
  - loki.yaml
  - node-exporter.yaml
  - prometheus.yaml
  - promtail.yaml
  - tempo.yaml
